/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import WealthManagement.Asset;
import WealthManagement.BankAccount;
import java.util.Vector;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

public class BankAccountForm extends javax.swing.JFrame {
    Vector<Asset> assets;
    JList assetList;
    
    boolean editing;
    BankAccount editAccount;
    JTextArea textArea;
    WealthManagerForm wmf;
    
    /**
     * Creates new form BankAccountForm
     */
    public BankAccountForm(){
        
    }
    
    public BankAccountForm(Vector<Asset> assets, JList assetList, WealthManagerForm wmf) {
        initComponents();
        this.assets = assets;
        this.assetList = assetList;
        this.wmf = wmf;
        
        this.editing = false;
        this.editAccount = null;
    }
    
    public BankAccountForm(BankAccount acc, JTextArea area, WealthManagerForm wmf)
    {
        initComponents();
        this.editing = true;
        this.editAccount = acc;
        this.textArea = area;
        this.wmf = wmf;
        
        this.nameTextField.setText(acc.toString());
        this.balanceTextField.setText(Double.toString(acc.getAssetValue()));       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        balanceTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bank Account");
        setName("Bank Account"); // NOI18N

        jLabel1.setText("Name");

        jLabel2.setText("Balance");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField)
                            .addComponent(balanceTextField))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(balanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        System.out.println(evt.getActionCommand());
        
        boolean valid = true;
        String name = this.nameTextField.getText().trim();
        double balance = 0;
        
        if (name.isEmpty())
        {
            valid = false;
            JOptionPane.showMessageDialog(this,
                    "Invalid name:\n" + this.nameTextField.getText(),
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
                
        try
        {
            balance =  Double.parseDouble(this.balanceTextField.getText());
        }
        catch (NumberFormatException ex)
        {
            valid = false;
            JOptionPane.showMessageDialog(this,
                    "Invalid balance:\n" + this.balanceTextField.getText(),
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        if (valid)
        {
            if (this.editing)
            {
                this.editAccount.setName(name);
                wmf.UpdateValue(-editAccount.getAssetValue());
                this.editAccount.setAssetValue(balance);
                wmf.UpdateValue(balance);
                this.textArea.setText(this.editAccount.getDetailString());
            }
            else
            {
                assets.add(new BankAccount(name, balance));
                wmf.UpdateValue(balance);
                assetList.setListData(assets);
            }        
            
            setVisible(false);  // hide window
            dispose();          // delete window
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);  // hide window
        dispose();          // delete window
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balanceTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
