/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import WealthManagement.Asset;
import WealthManagement.Car;
import WealthManagement.House;
import WealthManagement.Property;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

public class PropertyForm extends javax.swing.JFrame {
    Vector<Asset> assets;
    JList assetList;
    
    boolean editing;
    Property editProperty;
    JTextArea textArea;
    WealthManagerForm wmf;
    /**
     * Creates new form StockForm
     */
    public PropertyForm(Vector<Asset> assets, JList assetList, WealthManagerForm wmf) {
        initComponents();
        this.assets = assets;
        this.assetList = assetList;
        this.wmf = wmf;
   
        this.editing = false;
        this.editProperty = null;
    }
    
    public PropertyForm(Property prop, JTextArea area, String selectedItem, WealthManagerForm wmf)
    {
        initComponents();
        
        typeComboBox.setSelectedItem(selectedItem);
        typeComboBox.setEnabled(false);
        this.editing = true;
        this.editProperty = prop;
        this.textArea = area;
        this.wmf = wmf;
        
        this.nameTextField.setText(prop.toString());
        this.valueTextField.setText(Double.toString(prop.getAssetValue()));  
        this.debtTextField.setText(Double.toString(prop.getDebtAmount()));       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        valueTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        debtTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Property");
        setName("Bank Account"); // NOI18N

        jLabel1.setText("Name");

        jLabel2.setText("Value");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        valueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueTextFieldActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Debt");

        jLabel4.setText("Type");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Car", "House" }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField)
                            .addComponent(valueTextField)
                            .addComponent(debtTextField))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(valueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(debtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        System.out.println(evt.getActionCommand());
        
        boolean valid = true;
        String name = this.nameTextField.getText().trim();
        double value = 0;
        double debt = 0;
        
        if (name.isEmpty())
        {
            valid = false;
            JOptionPane.showMessageDialog(this,
                    "Invalid name:\n" + this.nameTextField.getText(),
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
                
        try
        {
            value =  Double.parseDouble(this.valueTextField.getText());
        }
        catch (NumberFormatException ex)
        {
            valid = false;
            JOptionPane.showMessageDialog(this,
                    "Invalid balance:\n" + this.valueTextField.getText(),
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        try
        {
            debt =  Double.parseDouble(this.debtTextField.getText());
        }
        catch (NumberFormatException ex)
        {
            valid = false;
            JOptionPane.showMessageDialog(this,
                    "Invalid quanity:\n" + this.debtTextField.getText(),
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        if (valid)
        {
            String propType = (String)typeComboBox.getSelectedItem();
            if (this.editing)
            {
                
                this.editProperty.setName(name);
                wmf.UpdateValue(-editProperty.getAssetValue());
                wmf.UpdateDebt(-editProperty.getDebtAmount());
                this.editProperty.setAssetValue(value);
                wmf.UpdateValue(value);
                wmf.UpdateDebt(debt);
                this.editProperty.setDebt(debt);
                this.textArea.setText(this.editProperty.getDetailString());
                
            }
            else{
                if (propType.equals("Car")){
                    assets.add(new Car(name, value, debt));
                    wmf.UpdateValue(value);
                    wmf.UpdateDebt(debt);
                }
                else if (propType.equals("House")){
                    assets.add(new House(name, value, debt));
                    wmf.UpdateValue(value);
                    wmf.UpdateDebt(debt);
                }
                assetList.setListData(assets);
                wmf.updateBars();
            }
                setVisible(false);  // hide window
                dispose();          // delete window
            
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);  // hide window
        dispose();          // delete window
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void valueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueTextFieldActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeComboBoxActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField debtTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox typeComboBox;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables
}
