/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import WealthManagement.Asset;
import WealthManagement.Stock;
import java.util.Vector;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

public class StockForm extends javax.swing.JFrame {
    Vector<Asset> assets;
    JList assetList;
    
    boolean editing;
    Stock editStock;
    JTextArea textArea;
    WealthManagerForm wmf;
    /**
     * Creates new form StockForm
     */
    public StockForm(Vector<Asset> assets, JList assetList, WealthManagerForm wmf) {
        initComponents();
        this.assets = assets;
        this.assetList = assetList;
        this.wmf = wmf;
        
        this.editing = false;
        this.editStock = null;
    }

    public StockForm(Stock stock, JTextArea area, WealthManagerForm wmf)
    {
        initComponents();
        this.editing = true;
        this.editStock = stock;
        this.textArea = area;
        this.wmf = wmf;
        
        this.nameTextField.setText(stock.toString());
        this.priceTextField.setText(Double.toString(stock.getPrice()));  
        this.quanityTextField.setText(Integer.toString(stock.getQuanity()));  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        quanityTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stock");
        setName("Bank Account"); // NOI18N

        jLabel1.setText("Ticker");

        jLabel2.setText("Price");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Quanity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTextField)
                            .addComponent(priceTextField)
                            .addComponent(quanityTextField))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(quanityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        System.out.println(evt.getActionCommand());
        
        boolean valid = true;
        String name = this.nameTextField.getText().trim();
        double price = 0;
        int quanity = 0;
        
        if (name.isEmpty())
        {
            valid = false;
            JOptionPane.showMessageDialog(this,
                    "Invalid name:\n" + this.nameTextField.getText(),
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
                
        try
        {
            price =  Double.parseDouble(this.priceTextField.getText());
        }
        catch (NumberFormatException ex)
        {
            valid = false;
            JOptionPane.showMessageDialog(this,
                    "Invalid balance:\n" + this.priceTextField.getText(),
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        try
        {
            quanity =  Integer.parseInt(this.quanityTextField.getText());
        }
        catch (NumberFormatException ex)
        {
            valid = false;
            JOptionPane.showMessageDialog(this,
                    "Invalid quanity:\n" + this.quanityTextField.getText(),
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        if (valid)
        {
            if (this.editing)
            {
                
                this.editStock.setName(name);
                wmf.UpdateValue(-editStock.getAssetValue());
                this.editStock.setPrice(price);
                this.editStock.setQuanity(quanity);
                wmf.UpdateValue(price*quanity);
                this.textArea.setText(this.editStock.getDetailString());
                setVisible(false);  // hide window
                dispose();  
            }
            else{
                assets.add(new Stock(name, price, quanity));
                wmf.UpdateValue(price*quanity);
                assetList.setListData(assets);
            }
                setVisible(false);  // hide window
                dispose();          // delete window
            
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);  // hide window
        dispose();          // delete window
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField quanityTextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
